### ISSUE TITLE
My project was broken because of layer orders

### ISSUE THREAD

**Issue by Bluecube5997thefan** [TurboWarp/sb3fix#13]
Please fix it

**Comment by GarboMuffin** [comment]
give me the project file

**Comment by Bluecube5997thefan** [comment]
here: https://drive.google.com/file/d/1Iqk0T7YvaKTSAJH0C7GI1sQ-WRK0rXok/view?usp=sharing

**Comment by GarboMuffin** [comment]
sb3fix can now patch up your project enough to make it load, HOWEVER the real bug is in that custom WebGL extension you are using. You need to contact whoever makes that so that they "stop putting their own drawable ID at the start of renderer._drawList, which corrupts projects" every time the extension loads.

**Comment by GarboMuffin** [comment]
Do note that before you loaded that extension, you saw this warning:

> Loading extensions without the sandbox is dangerous and should not be enabled if you don't know what you're doing.
>
> Unsandboxed extensions **can corrupt your project**, delete your settings, phish for passwords, and other bad things. The TurboWarp developers are not responsible for any resulting issues.

And because the extension corrupts your project each time it runs, you'll probably have to put it into sb3fix every time you save it until the extension is removed or fixed.
