### ISSUE TITLE
Help , i MADE THE BEST PROJECT ON SCRATCH , but it broke :( .

### ISSUE THREAD

**Issue by PerfectionCode** [TurboWarp/sb3fix#3]
here it is :( , please fix it and please , just please .try to keep the assets . https://drive.google.com/file/d/15tUf5U8YlmkGTNnIE0jCAcrS_x7qbO_2/view?usp=drive_link

**Comment by GarboMuffin** [comment]
make the link public

**Comment by PerfectionCode** [comment]
i did , but please , try to keep the assets :)

**Comment by GarboMuffin** [comment]
please try file > load restore point if you haven't already, before it gets overwritten

**Comment by PerfectionCode** [comment]
i wouldve done that , yet it was overwritten right away.
please try more . i will seriously appreciate it :(((

**Comment by GarboMuffin** [comment]
hi, this is what I was able to recovery: https://static.muffin.ink/sb3fix-3.sb3 most of it was not recoverable, sorry

the most likely cause for the corruption is that your project.json exceeded 100 MB in size because of the "World" and "Texture" lists which contain *way too much data*

we would like to prevent things like this from happening again; were you using the desktop app or website, and what operating system are you using?

**Comment by PerfectionCode** [comment]
I am using windows 10 pro , 64 bit , an i was using neither the website or the desktop . i was using a version that is google chrome but turbowarp . i think you understand , the version where it prompts you to download while you use the website.

**Comment by GarboMuffin** [comment]
nothing else I can do :(
